
server:
  port: 9005

spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/murugesan-narayan/cloud-config
          clone-on-start: true
          default-label: main
