server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
#  cloud:
#    config:
#      import-check:
#        enabled: false
  config:
    import: configserver:http://CONFIG-SERVICE
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: CONFIG-SERVICE
  zipkin:
    enabled: false
    base-url: http://localhost:9411

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/