server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://CONFIG-SERVICE
#  cloud:
#    config:
#      import-check:
#        enabled: false
  zipkin:
    enabled: false
    base-url: http://localhost:9411

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/